name: fer-vit
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _python_abi3_support=1.0
  - antlr-python-runtime=4.9.3
  - aom=3.6.0
  - blas=1.0
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - cairo=1.16.0
  - certifi=2025.11.12
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - cpython=3.10.18
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cuda-version=12.9
  - dav1d=1.2.1
  - expat=2.7.1
  - ffmpeg=4.3
  - filelock=3.17.0
  - fontconfig=2.14.1
  - freetype=2.13.3
  - fribidi=1.0.10
  - fsspec=2025.5.1
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.6.15
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - hf-xet=1.1.5
  - huggingface_hub=0.33.4
  - icu=73.1
  - idna=3.7
  - intel-openmp=2023.1.0
  - jinja2=3.1.6
  - jpeg=9e
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libavif=1.1.1
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.14.1.1
  - libcurand=10.3.10.19
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.22
  - libffi=3.4.4
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libglib=2.84.2
  - libgomp=15.1.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.7.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxml2=2.13.8
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.4.2
  - numpy=2.0.1
  - numpy-base=2.0.1
  - omegaconf=2.3.0
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.6.0
  - packaging=25.0
  - pcre2=10.42
  - pillow=11.3.0
  - pip=25.1
  - pixman=0.40.0
  - pthread-stubs=0.3
  - pycparser=2.21
  - pysocks=1.7.1
  - python=3.10.18
  - python-gil=3.10.18
  - python_abi=3.10
  - pytorch=2.5.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - readline=8.2
  - requests=2.32.4
  - safetensors=0.5.3
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tbb=2021.8.0
  - timm=1.0.17
  - tk=8.6.14
  - torchaudio=2.5.1
  - torchtriton=3.1.0
  - torchvision=0.20.1
  - tqdm=4.67.1
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - urllib3=2.5.0
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - absl-py==2.3.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - fonttools==4.60.1
      - grpcio==1.76.0
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - markdown==3.10
      - matplotlib==3.10.7
      - opencv-python==4.12.0.88
      - pandas==2.3.3
      - protobuf==6.33.0
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - six==1.17.0
      - sympy==1.13.1
      - taming-transformers==0.0.1
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - tzdata==2025.2
      - werkzeug==3.1.3
